dir_path:
  kind_config: /opt/kind
  challenge: ~/challenge
  go: "{{ playbook_dir }}/../challenges/golang/app"
  curl: "{{ playbook_dir }}/../challenges/linux/curl"
  webserver: "{{ playbook_dir }}/../challenges/linux/webserver"
  tinyapi: "{{ playbook_dir }}/../challenges/linux/tinyapi"
  psql: "{{ playbook_dir }}/../challenges/postgres"
  mongo: "{{ playbook_dir }}/../challenges/mongo-backup"
  prometheus_grafana: "{{ playbook_dir }}/../challenges/monitoring/prometheus"
  loki: "{{ playbook_dir }}/../challenges/monitoring/loki"
  tfdocker: "{{ playbook_dir }}/../challenges/iac/terraform/docker"
  rootpw_file: /root/rootpw

pub_keys:
  - "ssh-ed25519 BBBBC3NzaC1lZDI1NTE5AAAAIC18cEmgukkzGJCCRdEnEl7cAkUfj/77df7a7dsf7d7d k.islow@example.com"
