---
- hosts: all
  roles:
    - role: base
      tags: [base]

    - role: ssh-keys
      tags: [ssh-keys]

    - role: kind
      tags: [kind]

    - role: go-app-challenge
      tags: [go-app-challenge]

    - role: linux-curl-challenge
      tags: [linux-curl-challenge]

    - role: linux-webserver-challenge
      tags: [linux-webserver-challenge]

    - role: linux-tinyapi-challenge
      tags: [linux-tinyapi-challenge]

    - role: postgres-docker-challenge
      tags: [postgres-docker-challenge]

    - role: mongodb-backup-challenge
      tags: [mongodb-backup-challenge]

    - role: prometheus-challenge
      tags: [prometheus-challenge]

    - role: loki-challenge
      tags: [loki-challenge]
